[tool.black]
line-length = 999
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
| pyproject\.toml
'''
preview = false

[tool.isort]
profile = "black"
line_length = 999
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true
force_sort_within_sections = true
known_first_party = ["fincli"]
